spring:
  flyway:
    clean-disabled: false
    
  config:
    activate:
      on-profile: test

# Applikationsspezifische Einstellungen
app:
  server:
    port: ${TEST_SERVER_PORT}
  mysql:
    url: jdbc:${MYSQL_URL}://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_TEST_DB}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_TEST_USERNAME}
    password: ${MYSQL_TEST_PASSWORD}
  http2:
   enabled: false
  ssl:
   enabled: false