name: Weekly Docker Push to GHCR – Omnixys Transaction Service

on:
  schedule:
    - cron: '0 3 * * 1'  # Jeden Montag um 03:00 UTC
  workflow_dispatch:  # Manuelles Triggern möglich

permissions:
  contents: read
  id-token: write # ← WICHTIG für Cosign ohne Schlüssel (keyless signing)

env:
    COSIGN_EXPERIMENTAL: "true"
    IMAGE_NAME: ${{ secrets.DOCKER_USER }}/${{ secrets.SERVICE }}
    # IMAGE_NAME: ghcr.io/${{ github.repository }}
    # IMAGE_NAME: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}
jobs:
  sync-current-date:
        outputs:
            current_date: ${{ steps.set_date.outputs.CURRENT_DATE }}
        name: Sync CURRENT_DATE in GitHub Org
        runs-on: ubuntu-latest
        permissions:
          contents: read
        steps:

          - name: Set CURRENT_DATE
            id: set_date
            run: |
              DATE=$(date +'%Y-%m-%d')
              echo "CURRENT_DATE=$DATE" >> $GITHUB_OUTPUT

          - name: Update CURRENT_DATE in org variable
            env:
              GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Classic PAT mit org:admin
            run: |
              CURRENT_DATE="${{ steps.set_date.outputs.CURRENT_DATE }}"

              if [ -z "$CURRENT_DATE" ]; then
                echo "❌ CURRENT_DATE ist leer!"
                exit 1
              fi

              ORG_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1)
              VAR_NAME="CURRENT_DATE"

              echo "📅 Neuer Wert für $VAR_NAME: $CURRENT_DATE"

              EXISTING=$(curl -s \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/orgs/$ORG_NAME/actions/variables/$VAR_NAME \
                | jq -r '.value')

              if [ "$EXISTING" != "$CURRENT_DATE" ]; then
                echo "🔁 Aktualisiere $VAR_NAME von $EXISTING auf $CURRENT_DATE"
                curl -s -X PATCH \
                  -H "Authorization: Bearer $GH_TOKEN" \
                  -H "Accept: application/vnd.github+json" \
                  https://api.github.com/orgs/$ORG_NAME/actions/variables/$VAR_NAME \
                  -d "{\"value\": \"${CURRENT_DATE}\"}"
              else
                echo "✅ CURRENT_DATE ist bereits aktuell: $CURRENT_DATE"
              fi

  docker-push:
    runs-on: ubuntu-latest
    needs: sync-current-date
    env:
        CURRENT_DATE: ${{ needs.sync-current-date.outputs.current_date }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Latest Docker Image from Docker Hub
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest

      - name: Tag Docker Image for GHCR
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }}

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker Image with cosign (OIDC/GitHub)
        run: |
            cosign sign --yes ghcr.io/${{ env.IMAGE_NAME }}:${{ env.CURRENT_DATE }}
            cosign sign --yes ghcr.io/${{ env.IMAGE_NAME }}:latest
